# handlers file for apache2
# - name: Enable apache2 service
#   service:
#     name: apache2
#     enabled: yes

- name: Start apache2 service
  service:
    name: apache2
    state: started

- name: Reload apache2
  service:
    name: apache2
    state: reloaded

- name: restart apache2
  service: 
    name: apache2
    state: restarted
